Changing dotdrop command to have optional --user arg

diff --git a/user/dotdrop b/user/dotdrop
--- a/user/dotdrop
+++ b/user/dotdrop
@@ -4,10 +4,10 @@
 # any dorectory, and will run the dotdrop command for user/root, or for both.
 #
 # Arguments:
-#   - $1: the user dotdrop will be executed for. Can be one of 'user', 'root'
-#         or 'both'.
-#   - $2: the dotdrop command that will be executed.
-#   - $3+: options and arguments for dotdrop.
+#   - --user USER: the user dotdrop will be executed for. Can be one of 'user',
+#       'root' or 'both'. Optional, defaults to 'user' for unprivileged users
+#        and to 'root' for root.
+#   - $@: dotdrop arguments.
 #
 # Environment:
 #   - $DOTFILES_HOME: the directory where Pipfile and dotdrop.sh are located.
@@ -23,33 +23,50 @@ DOTFILES_HOME="${DOTFILES_HOME:-$HOME/Files/Programming/sys/dotfiles}"
 # Input processing
 #######################################
 
-WHO="$1"
-CMD="$2"
-shift 2
+WHO=''
+CMD=''
+ARGS=()
 
-WRONG_USER=''
+CURR_ARG=''
+for ARG in "$@"; do
+    case "$CURR_ARG" in
+        'user')
+            WHO="$ARG"
+            continue
+            ;;
+    esac
+    case "$ARG" in
+        '--user'|'-U')
+            CURR_ARG='user'
+            ;;
+        *)
+            # Accorting to dotdrop syntax, the first argument must be the
+            # command.
+            [ -z "$CMD" ] && {
+                CMD="$ARG"
+                continue
+            }
+
+            # Relative paths need to be resolved before cd-ing into
+            # $DOTFILES_HOME, otherwise they become afterwards
+            [ -e "$ARG" ] && ARG="$(readlink -f "$ARG")"
+            ARGS+=("$ARG")
+            ;;
+    esac
+done
+
 case "$WHO" in
     user|root|both)
         ;;
     '')
-        WRONG_USER='no user'
+        [ "$USER" = 'root' ] && WHO='root' || WHO='user'
         ;;
     *)
-        WRONG_USER="'$WHO' user"
+        echo >&2 "Error: '$WHO' user given. Muse be one of 'user', 'root' or" \
+            "'both'"
+        exit 1
         ;;
 esac
-[ -n "$WRONG_USER" ] && {
-    echo >&2 "Error: $WRONG_USER given. Muse be one of 'user', 'root' or" \
-        "'both'"
-    exit 1
-}
-
-# Relative paths need to be resolved before cd-ing, otherwise they won't work
-ARGS=()
-for ARG in "$@"; do
-    [ -e "$ARG" ] && ARG="$(readlink -f "$ARG")"
-    ARGS+=("$ARG")
-done
 
 #######################################
 # Executing dotdrop
@@ -67,7 +84,7 @@ esac
 
 case "$WHO" in
     root|both)
-        sudo -E pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' \
+        sudo pipenv run bash dotdrop.sh "$CMD" -c 'config-root.yaml' \
             "${ARGS[@]}"
         ;;
 esac
